function TV(data) {
  "use strict";

  const CHANNELS = {
    1: "BBC1EAST/BBC One East",
    2: "BBC2/BBC Two",
    3: "ITV1ANG/ITV1 (Anglia)",
    4: "C4/Channel 4",
    5: "CH5/Channel 5",
    6: "ITV2/ITV2",
    7: "THACAUK/That's Cambridge TV",
    9: "BBC4/BBC Four",
    10: "ITVTHREE/ITV3",
    11: "SKYART1/Sky Arts",
    12: "QUEST/Quest",
    13: "E4/E4",
    14: "FILM4UK/Film4",
    16: "QVCUK/QVC (European)",
    17: "REALLY/Really UKTV",
    18: "MORE4/More 4",
    19: "DAVE/Dave",
    20: "DRAMAUK/Drama",
    21: "5USA/5USA",
    22: "IDLFV/Ideal World",
    23: "DAVEJV/Dave Ja Vu",
    25: "ITV4/ITV4",
    26: "YESTDAY/Yesterday",
    27: "ITVBE/ITV BE",
    30: "4MUSIC/4Music",
    31: "5ST/5 Star",
    32: "PARNSVM/Paramount Network",
    33: "GRETMOV/Great Movies",
    35: "PICKTV/Pick TV",
    36: "QVCBEAU/QVC Beauty",
    37: "QVCSTFV/QVC Style",
    38: "DMAXE/DMAX",
    39: "QREDUK/Quest Red",
    40: "CBSJUVM/CBS Justice",
    41: "GRTMACT/Great Movies Action",
    42: "FOODNET/Food Network",
    43: "HGTVUK/HGTV",
    44: "GEMTVFV/Gems TV",
    47: "CHALL/Challenge TV",
    48: "4SEVEN/4Seven",
    49: "GREATUK/Great TV",
    50: "JEWELCH/The Jewellery Channel",
    51: "GRTMCL/Great Movies Classic",
    55: "5SELECT/5SELECT",
    56: "SMTSNSD/Smithsonian Channel SD",
    63: "BLZEFV/Blaze",
    64: "FREESPO/Free Sports",
    65: "TBNUK/TBN UK",
    66: "CBSRELT/CBS Reality",
    67: "CBSDRFV/CBS Drama",
    68: "HORROR/Horror Channel",
    71: "JEWELMK/Jewellery Maker",
    72: "SHOPQUA/Shopping Quarter",
    76: "NOW80UK/Now 80s",
    77: "TCCUK/TCC",
    81: "TALKPIC/Talking Pictures TV",
    82: "TOGETUK/Together",
    84: "PBSUKVM/PBS",
    91: "THATGOLD/That's TV Gold",
    94: "IDEALEX/Ideal Extra",
    95: "CREATFV/Create and Craft",
    96: "BRITFRC/British Forces TV",
    101: "BBC1LDH/BBC One HD (London)",
    102: "BBC2HD/BBC Two HD",
    103: "ITV1HDS/ITV1 HD (Meridian, Anglia)",
    104: "C4HD/Channel 4 HD",
    105: "CH5HD/Channel 5 HD",
    106: "BBC4HD/BBC Four HD",
    107: "BBCNWHD/BBC News HD",
    111: "QVCUKHD/QVC HD",
    112: "QVCBHFV/QVC Beauty HD",
    113: "RTUKHD/RT HD",
    114: "QUESHDV/Quest HD",
  };

  var table = document.getElementById("main");
  var tbody = table.getElementsByTagName("tbody")[0];
  document.getElementById("log").textContent = JSON.stringify(data, null, 2);
}
